server:
  port: 8080
#数据源配置
spring:
  datasource:
    username: root
    password: 11
    url: jdbc:mysql:///nass
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis配置
mybatis:
  mapper-locations: classpath:cn/itsource/*/mapper/*Mapper.xml #可以不配置
  type-aliases-package: cn.itsource.domain,cn.itsource.query

#日志
logging:
  level:
    cn:
      itsource: debug